---
# Credentials for CVP and EOS Switches
ansible_user: arista
ansible_password: "{{ lookup('env', 'LABPASSPHRASE') }}"
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

# arista.avd.cv_deploy role parameters
cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc1MDQ0MDYzMzQwNjI3MjMzMTYsImRzbiI6InNlcnZpY2UiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxNzU3MTMxMTk5LCJpYXQiOjE3NTYzMDc3OTIsIm9naSI6Mywib2duIjoiRGVmYXVsdCIsInNpZCI6ImU5MWRiNGYyOGM3NTBhNTc3YWI4YTIyMWU3NTJkYmI1YjcyZDk4YTE1YTM4YTA0MDNhNDNkYjg4NWFhMTY4NWQtak5qbXh4dVBZeU5rZXh3dmFWVEJjblRJTUpnTFE3M01rU2ZvSjFSMiJ9.OPt18mWang0qOP7ob7TIN3b5VbEVehKLzCRsczHQlVmgc0mniO3rT07ckswNHUfF09vdPEwPSAk-62kwBkIsF9spb8WLJxQNMnUqh4EIx-tv8j6SmrxhQVZXtyOvIekgn0UZjtgOs0FMptx5mrtPcF75EJ0OM-EmmlM10Ce9b2SQWhtD-8vONxagAymN4kp-utE47BXjvASNf9nLFVEuUB56ZzasSGV0_MoAzIxIjCv-cl3EcFZhKd8OCL9sAi_ZMy7oer7zC7ukXnXUh5A4Pu4km9eRaAE9ZoBfgrUytfQhBAj4gtO2VKhTNkC1Q2xwrrbn0auKvW_MTrf7MPRLRSv1QYGxygJg5M_0wJmDHPfrE-KMriM78eJvGLMFdDwB71_tqPD7k6dPjxFKRQAU7UyKo4Z-iW5AdAWgH9Sg46nUQmcF8kxP-MgoJNJiDalSAJF79rKfEIpwkxJWUs5QPI4JpC1GdepSuKDz-ClPHYdq-hRe7nqubsOU6g_OcMsQxbKVB4hxDOUF05L8gDoUnt62T3V0kfCNJYoChGzctHfV7iY0bedlcQlQfPbjsjdNMbtNmENEoOvPftaRhDkj5i-YddsXvaAT6US0-JRpuAOPjELP9YtPfiFeOVwZhpD3-Uj3ptvLrIgCUpo1MaEzufchNHfe6RucfUbNbBlvfYI
cv_server: cvp
cv_verify_certs: false

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
    ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"

# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: 192.168.0.1
      iburst: true
      local_interface: Management0

# Domain/DNS
dns_domain: atd.lab

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.0.5:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: token
    token_file: "/tmp/token"
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# CVP node variables
cv_collection: v3
execute_tasks: true
